# Publish package on release branch if it's tagged with 'v*'

name: release & publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    name: Publish documentation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [3.10]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry tox tox-gh-actions

      - name: list files
        run: ls -l .

      - name: build documentation
        run: |
          poetry install
          poetry run mkdocs build

      - name: publish documentation
        run: poetry run mkdocs gh-deploy --force
